### Register User
POST http://localhost:8000/api/v1/auth/register
Content-Type: application/json

{
  "email": "doel.jaelani@example.com",
  "password": "securePassword123"
}

### Login User
POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
  "email": "doel.jaelani@example.com",
  "password": "securePassword123"
}

### Get my profile
GET http://localhost:8000/api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk2YTA5NDM0LThmMmEtNDZhZS04NzU1LWJlZjlhNDU2ZTM1YSIsImVtYWlsIjoia2FiaXphbEBleGFtcGxlLmNvbSIsImlhdCI6MTc1MDE4NzE0MiwiZXhwIjoxNzUwMjczNTQyfQ.y1STqT0at1Bs0MjbIsr5Ky37H9OA8TxVjBUQnGsVHls

### Get all users
GET http://localhost:8000/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk2YTA5NDM0LThmMmEtNDZhZS04NzU1LWJlZjlhNDU2ZTM1YSIsImVtYWlsIjoia2FiaXphbEBleGFtcGxlLmNvbSIsImlhdCI6MTc1MDE4NzE0MiwiZXhwIjoxNzUwMjczNTQyfQ.y1STqT0at1Bs0MjbIsr5Ky37H9OA8TxVjBUQnGsVHls

### Update user
PATCH http://localhost:8000/api/v1/users/96a09434-8f2a-46ae-8755-bef9a456e35a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk2YTA5NDM0LThmMmEtNDZhZS04NzU1LWJlZjlhNDU2ZTM1YSIsImVtYWlsIjoia2FiaXphbEBleGFtcGxlLmNvbSIsImlhdCI6MTc1MDE4NzE0MiwiZXhwIjoxNzUwMjczNTQyfQ.y1STqT0at1Bs0MjbIsr5Ky37H9OA8TxVjBUQnGsVHls

{
  "email": "lazibak@example.com"
}

### Delete user
DELETE http://localhost:8000/api/v1/users/7065718c-6907-4a36-97aa-05c2d3395a86
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjcwNjU3MThjLTY5MDctNGEzNi05N2FhLTA1YzJkMzM5NWE4NiIsImVtYWlsIjoiZG9lbC5qYWVsYW5pQGV4YW1wbGUuY29tIiwiaWF0IjoxNzUwMTg3MzEwLCJleHAiOjE3NTAyNzM3MTB9.ymQOTU3xGkhaGehM3V-E1Nzjo21nbmTmu1Jolofx3LU



### Create Project
POST http://localhost:8000/api/v1/projects
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc5MDkxZWUwLTY4NDgtNDVmOS04MWU4LWVkMzYxYmJjZDc1ZiIsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3NTAxNzcwMDQsImV4cCI6MTc1MDI2MzQwNH0.XtkkIOJx2bEjdESc116GyWKXJnSqFOwzn9evhMKsYc8

{
  "name": "Team Webdev"
}

### Invite member by email
POST http://localhost:8000/api/v1/projects/791e3cdc-4ac5-4b3d-b3c9-72b6cf08800f/invite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc5MDkxZWUwLTY4NDgtNDVmOS04MWU4LWVkMzYxYmJjZDc1ZiIsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3NTAxNzcwMDQsImV4cCI6MTc1MDI2MzQwNH0.XtkkIOJx2bEjdESc116GyWKXJnSqFOwzn9evhMKsYc8

{
  "email": "devscale@example.com"
}

### Get Project Detail
GET http://localhost:8000/api/v1/projects/75cab097-4f31-41b2-b42f-00f1496f7c80
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc5MDkxZWUwLTY4NDgtNDVmOS04MWU4LWVkMzYxYmJjZDc1ZiIsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3NTAxNzcwMDQsImV4cCI6MTc1MDI2MzQwNH0.XtkkIOJx2bEjdESc116GyWKXJnSqFOwzn9evhMKsYc8


### Update Project
PATCH http://localhost:8000/api/v1/projects/75cab097-4f31-41b2-b42f-00f1496f7c80
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc5MDkxZWUwLTY4NDgtNDVmOS04MWU4LWVkMzYxYmJjZDc1ZiIsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3NTAxNzcwMDQsImV4cCI6MTc1MDI2MzQwNH0.XtkkIOJx2bEjdESc116GyWKXJnSqFOwzn9evhMKsYc8

{
  "name": "Team WebDev"
}

### Delete Project
DELETE http://localhost:8000/api/v1/projects/75cab097-4f31-41b2-b42f-00f1496f7c80
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc5MDkxZWUwLTY4NDgtNDVmOS04MWU4LWVkMzYxYmJjZDc1ZiIsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3NTAxNzcwMDQsImV4cCI6MTc1MDI2MzQwNH0.XtkkIOJx2bEjdESc116GyWKXJnSqFOwzn9evhMKsYc8


### Create task
POST http://localhost:8000/api/v1/791e3cdc-4ac5-4b3d-b3c9-72b6cf08800f/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk2YTA5NDM0LThmMmEtNDZhZS04NzU1LWJlZjlhNDU2ZTM1YSIsImVtYWlsIjoia2FiaXphbEBleGFtcGxlLmNvbSIsImlhdCI6MTc1MDE3NzQ5OSwiZXhwIjoxNzUwMjYzODk5fQ.fq-6TrV5lLAEAobgxORurEnVxWY204X5QD2tNRYqLwY

{
  "title": "Fix bug",
  "description": "Fix authentication bug",
  "status": "TODO",
  "assigneeId": "96a09434-8f2a-46ae-8755-bef9a456e35a"
}

### Get tasks for a project
GET http://localhost:8000/api/v1/791e3cdc-4ac5-4b3d-b3c9-72b6cf08800/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk2YTA5NDM0LThmMmEtNDZhZS04NzU1LWJlZjlhNDU2ZTM1YSIsImVtYWlsIjoia2FiaXphbEBleGFtcGxlLmNvbSIsImlhdCI6MTc1MDE3NzQ5OSwiZXhwIjoxNzUwMjYzODk5fQ.fq-6TrV5lLAEAobgxORurEnVxWY204X5QD2tNRYqLwY

### Update task
PATCH http://localhost:8000/api/v1/task/3dbedd0f-7ebd-4b40-a32c-5d847fc7629e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk2YTA5NDM0LThmMmEtNDZhZS04NzU1LWJlZjlhNDU2ZTM1YSIsImVtYWlsIjoia2FiaXphbEBleGFtcGxlLmNvbSIsImlhdCI6MTc1MDE3NzQ5OSwiZXhwIjoxNzUwMjYzODk5fQ.fq-6TrV5lLAEAobgxORurEnVxWY204X5QD2tNRYqLwY


{
  "status": "DONE"
}

### Delete Task
DELETE http://localhost:8000/api/v1/task/540f3bef-093b-4317-b307-41be26aa6b24
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk2YTA5NDM0LThmMmEtNDZhZS04NzU1LWJlZjlhNDU2ZTM1YSIsImVtYWlsIjoia2FiaXphbEBleGFtcGxlLmNvbSIsImlhdCI6MTc1MDE3NzQ5OSwiZXhwIjoxNzUwMjYzODk5fQ.fq-6TrV5lLAEAobgxORurEnVxWY204X5QD2tNRYqLwY

